name: Update library.json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # daily 09:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/validate library.json
        run: |
          node -e "
          const fs=require('fs');
          const p='library.json';
          const raw=fs.readFileSync(p,'utf8');
          const data=JSON.parse(raw); // throws if invalid
          // ensure array or {items:[]}
          const items=Array.isArray(data)?data:(data.items||[]);
          if(!Array.isArray(items)) throw new Error('library.json must be an array or {items:[]}');
          // bump timestamp so Render picks up the change if needed
          if(!Array.isArray(data)){ data.updatedAt=new Date().toISOString(); fs.writeFileSync(p, JSON.stringify(data,null,2)); }
          "

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore: auto-validate library.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
